title: Gizem Ã–ge
logo: /assets/photo (1).png
description: 2x Datathon Winner | Data Analytics Professional | AI/ML Problem Solver | Driving Insights with Data
show_downloads: false
theme: jekyll-theme-minimal
